- name: Compute Engine Instance 
  hosts: buildhost
  tasks:
    - name: "Build Jenkins instance"
      gce:
        instance_names: klltest
        zone: us-east1-c
        machine_type: g1-small
        image: centos-7
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata : '{ "startup-script" : "yum -y update" }'
      register: gce

    - name: Save host data
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: gce_instances_ips
      with_items: "{{ gce.instance_data }}"

    - name: Wait for SSH for instances
      wait_for:
        delay: 1
        host: "{{ item.public_ip }}"
        port: 22
        state: started
        timeout: 60
      with_items: "{{ gce.instance_data }}"

- name: Configure hosts
  hosts: gce_instances_ips
  become: true
  roles:
    - baseline
    - jenkins

